using StudentManagementAPI.EntityFrameworkCore;
using Xunit;

namespace StudentManagementAPI.EntityFrameworkCore;

public class StudentManagementAPIEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<StudentManagementAPIEntityFrameworkCoreFixture>
{

}
